### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by liduang** [ryanxingql/winner-ntire22-vqe#3]
1080p的120帧视频做2倍超分，T4GPU 16G显存，单卡一直报RuntimeError: CUDA out of memory.
好像是计算一阶光流这里报错。求教如何解决
Traceback (most recent call last):
  File "my_vsr.py", line 40, in <module>
    output = restoration_video_inference(model, input_dir, window_size, start_idx, filename_tmpl, max_seq_len)
  File "/home/hicon/video/TaoMC2/stage1/mmedit/apis/restoration_video_inference.py", line 123, in restoration_video_inference
    result = model(lq=data, test_mode=True)['output'].cpu()
  File "/home/hicon/.conda/envs/mmtest/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hicon/.conda/envs/mmtest/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 110, in new_func
    return old_func(*args, **kwargs)
  File "/home/hicon/video/TaoMC2/stage1/mmedit/models/restorers/basic_restorer.py", line 75, in forward
    return self.forward_test(lq, gt, **kwargs)
  File "/home/hicon/video/TaoMC2/stage1/mmedit/models/restorers/basicvsr.py", line 177, in forward_test
    output = self.generator(lq)
  File "/home/hicon/.conda/envs/mmtest/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hicon/video/TaoMC2/stage1/mmedit/models/backbones/submission/basicvsr_pp_flow5v2.py", line 426, in forward
    flows_forward, flows_backward = self.compute_flow(lqs_downsample)
  File "/home/hicon/video/TaoMC2/stage1/mmedit/models/backbones/submission/basicvsr_pp_flow5v2.py", line 192, in compute_flow
    flows_backward = [self.spynet(lqs_1, lqs_2).view(n, t - 1, 2, h, w)]  # 一阶光流
  File "/home/hicon/.conda/envs/mmtest/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hicon/video/TaoMC2/stage1/mmedit/models/backbones/sr_backbones/basicvsr_net.py", line 370, in forward
    input=self.compute_flow(ref, supp),
  File "/home/hicon/video/TaoMC2/stage1/mmedit/models/backbones/sr_backbones/basicvsr_net.py", line 339, in compute_flow
    ], 1))
  File "/home/hicon/.conda/envs/mmtest/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hicon/video/TaoMC2/stage1/mmedit/models/backbones/sr_backbones/basicvsr_net.py", line 444, in forward
    return self.basic_module(tensor_input)
  File "/home/hicon/.conda/envs/mmtest/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hicon/.conda/envs/mmtest/lib/python3.7/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/hicon/.conda/envs/mmtest/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hicon/.conda/envs/mmtest/lib/python3.7/site-packages/mmcv/cnn/bricks/conv_module.py", line 201, in forward
    x = self.conv(x)
  File "/home/hicon/.conda/envs/mmtest/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hicon/.conda/envs/mmtest/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/hicon/.conda/envs/mmtest/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 396, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 3.92 GiB (GPU 0; 14.76 GiB total capacity; 9.24 GiB already allocated; 3.51 GiB free; 10.22 GiB reserved in total by PyTorch)

**Comment by ryanxingql** [comment]
您好，根据报错提示，显存只差一点点就够了。该模型是拿来打比赛的，我们是在32GB显卡上使用的。如果您是比赛需要，建议您还是找一块稍微大一点的显卡。
